name: Check for Changesets

on:
  pull_request:
    branches:
      - '*'
    # paths:
    #   - 'python/**'
    #   - 'typescript/**'

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check for missing changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false # We don't need to install root dependencies for this check

      - run: pnpm add human-id

      # Need to determine which paths were changed to conditionally run the checks
      # This uses the dorny/paths-filter action to check changed files
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - 'python/**'
            typescript:
              - 'typescript/**'

      - name: Check for Python changesets
        # Only run this step if python files were changed
        if: steps.filter.outputs.python == 'true'
        id: python-check
        uses: changesets/action@v1
        continue-on-error: true
        with:
          cwd: ./python
          version: false
          publish: false
          setupGitUser: true
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for TypeScript changesets
        # Only run this step if typescript files were changed
        if: steps.filter.outputs.typescript == 'true'
        id: typescript-check
        uses: changesets/action@v1
        continue-on-error: true
        with:
          cwd: ./typescript
          version: false
          publish: false
          setupGitUser: true
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR if Python changes missing changeset
        if: steps.filter.outputs.python == 'true' && steps.python-check.outputs.hasChangesets == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const humanId = require('human-id')

            const getNewChangesetTemplate = (changedPackages: string[], title: string) =>
              encodeURIComponent(`---
            ${changedPackages.map((x) => `"${x}": patch`).join("\n")}
            ---

            ${title}
            `);

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Missing Python Changeset 🐍
              
              Changes to the Python package were detected, but no changeset was found.
              Merging this PR will not cause a version bump for the Python package.
              
              If these changes should not result in a new version, you're good to go. **If these changes should result in a version bump, you need to add a changeset.**

              [Click here to learn what changesets are, and how to add one](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).

              [Click here if you're a maintainer who wants to add a changeset to this PR](${
                context.payload.pull_request.head.repo.html_url
              }/new/${
                context.payload.pull_request.head.ref
              }?filename=python/.changeset/${humanId({
                separator: "-",
                capitalize: false,
              })}.md&value=${getNewChangesetTemplate(
                changedPackages,
                context.payload.pull_request.title
              )})
              
              Alternatively, you can add a changeset by running:
              \`\`\`
              cd python
              pnpm changeset
              \`\`\`
              
              This will help document your changes and ensure proper versioning.`
            })

      - name: Comment on PR if TypeScript changes missing changeset
        if: steps.filter.outputs.typescript == 'true' && steps.typescript-check.outputs.hasChangesets == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Missing TypeScript Changeset 📝
              
              Changes to the TypeScript package were detected, but no changeset was found.
              
              Please add a changeset by running:
              \`\`\`
              cd typescript
              pnpm changeset
              \`\`\`
              
              This will help document your changes and ensure proper versioning.`
            })

      - name: Fail if changesets are missing
        if: (steps.filter.outputs.python == 'true' && steps.python-check.outputs.hasChangesets == 'false') || (steps.filter.outputs.typescript == 'true' && steps.typescript-check.outputs.hasChangesets == 'false')
        run: |
          echo "❌ Missing changesets detected. Please add changesets to document your changes."
          exit 1
