name: Publish Python Package

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'python/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing
      contents: write # Required to push tags and commit version updates
    environment: pypi

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for changeset changelog generation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest

      - name: Run tests
        run: |
          cd python
          python -m pytest tests/ -v

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10 # Match user's pnpm version
          run_install: true

      - name: Version Python package using Changesets

        id: version
        working-directory: python
        run: |
          echo "Initializing pnpm project..."
          touch pnpm-workspace.yaml
          pnpm init

          # Extract current version from setup.py
          CURRENT_VERSION=$(grep "version=['\"]" setup.py | cut -d "'" -f 2 | cut -d '"' -f 2)
          if [ -z "$CURRENT_VERSION" ]; then
            echo "Error: Could not extract current version from setup.py."
            exit 1
          fi
          echo "Current version from setup.py: $CURRENT_VERSION"

          pnpm pkg set name=brainyflow
          pnpm pkg set version=$CURRENT_VERSION # Use extracted version

          echo "Running changeset version..."
          # Run changesets. This might create/update package.json in the current dir (python/)
          pnpm dlx @changesets/cli version

          echo "Extracting potential new version from python/package.json..."
          NEW_VERSION=$(grep '"version":' package.json | cut -d '"' -f 4)
          if [ -z "$NEW_VERSION" ]; then
            echo "Error: Could not extract version from python/package.json even though the file exists."
            exit 1
          fi

          echo "Comparing versions: Current ($CURRENT_VERSION) vs Potential New ($NEW_VERSION)"
          if [ "$CURRENT_VERSION" == "$NEW_VERSION" ]; then
            echo "No version change detected in python/package.json."
            echo "Exiting step gracefully as no version bump occurred."
            echo "has_changes=false" >> $GITHUB_OUTPUT
            exit 0 # Exit successfully, no publish needed
          fi

          # Version has changed, proceed with update
          echo "Version changed to $NEW_VERSION. Updating setup.py..."
          # Use a temporary file for sed compatibility on different systems (like macOS)
          sed -i.bak "s/version=['\"].*['\"]/version='$NEW_VERSION'/" setup.py
          rm setup.py.bak # Remove backup file
          echo "setup.py content after update:"
          cat setup.py

          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Prepare README
        if: steps.version.outputs.has_changes == 'true'
        working-directory: python
        run: |
          cp ../README.md .

      - name: Build Python package
        if: steps.version.outputs.has_changes == 'true'
        working-directory: python
        run: |
          python -m build

      - name: Publish to PyPI
        if: steps.version.outputs.has_changes == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/
          skip-existing: true

      - name: Commit and push version bump
        if: steps.version.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update PY version and publish'

          file_pattern: 'python/setup.py python/.changeset/* python/package.json python/CHANGELOG.md'

      - name: Extract changelog text
        if: steps.version.outputs.has_changes == 'true'
        id: changelog_text # Changed id for clarity
        run: |
          CHANGELOG_CONTENT=$(node .github/scripts/extract-changelog-text.js python ${{ steps.version.outputs.new_version }})
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: steps.version.outputs.has_changes == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: python-v${{ steps.version.outputs.new_version }}
          release_name: Python Package v${{ steps.version.outputs.new_version }}
          body: |
            ## BrainyFlow Python Package v${{ steps.version.outputs.new_version }}

            ${{ steps.changelog.outputs.changelog }}

            ### Installation

            pip install brainyflow


            ### PyPI Package
            🐍 [View on PyPI](https://pypi.org/project/brainyflow/${{ steps.version.outputs.new_version }}/)
          draft: false
          prerelease: false

      - name: Notify Discord
        if: steps.version.outputs.has_changes == 'true' && env.DISCORD_WEBHOOK_URL != ''
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          node .github/scripts/discord-notify.js \
            "$DISCORD_WEBHOOK_URL" \
            "BrainyFlow Python" \
            "${{ steps.version.outputs.new_version }}" \
            "${{ steps.changelog.outputs.changelog }}" \
            "${{ github.server_url }}/${{ github.repository }}"
